version: '3.8'
services:
  express-knex:
    build: '.'
    ports:
      - '8081:8080'
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
<<<<<<< HEAD
      - DB_USERNAME=root
      - DB_PASSWORD=P@ssw0rd
=======
      - DB_USERNAME=db-remote
      - DB_PASSWORD=DbVpsP@ssw0rd123!@#
>>>>>>> 595852aa62e97bbce6aa0a58de8fd3217c930978
    extra_hosts:
      - "host.docker.internal:host-gateway"
