version: '3.8'
services:
  danfood-backend:
    build: '.'
    ports:
      - '8081:8080'
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"