version: '3.8'
services:
  express-knex:
    build: '.'
    ports:
      - '8081:8080'
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    command: bash -c "npm run knex && npm run start"