version: '3.8'
services:
  express-knex:
    build: '.'
    ports:
      - '8081:8080'
    env_file:
      - .env
    environment:
      - DB_HOST=172.17.0.1
      - DB_USERNAME=db-remote
      - DB_PASSWORD='DbVpsPassword123!@#'